### ISSUE TITLE
When will it run YOLOV3

### ISSUE THREAD

**Issue by yedajiang44** [SciSharp/SciSharp-Stack-Examples#14]
I want to run YOLOV3, but there are some errors。。。

**Comment by openmll** [comment]
me too, and I can run YoloV3 with Tensorflow1.5 not 2.X

**Comment by Esther2013** [comment]
YOLOv3 is support by latest release.

**Comment by yedajiang44** [comment]
of tf 2.0？？

**Comment by Esther2013** [comment]
@yedajiang44 Correct.

**Comment by yedajiang44** [comment]
Enabled yolov3 and get some  error @Esther2013 

```
Microsoft Windows NT 6.2.9200.0
2021-02-09 08:34:33.602211: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
TensorFlow Binary v1.15.1
TensorFlow.NET v0.15.1.0
[0]: Hello World
[1]: Basic Operations
[2]: NN XOR
[3]: Linear Regression
[4]: Logistic Regression
[5]: Naive Bayes Classifier
[6]: Nearest Neighbor
[7]: Digits Recognition Neural Network
[8]: MNIST CNN
[9]: MNIST RNN
[10]: MNIST LSTM
[11]: CnnInYourOwnData
[12]: Fully Connected Neural Network
[13]: Convert TensorFlow Model to OpenCv
[14]: Image Recognition Inception
[15]: Retrain Classifier With InceptionV3
[16]: Object Detection
[17]: CNN Text Classification
[18]: Word2Vec
[19]: YOLOv3
Choose one example to run, hit [Enter] to run all: 19
2021/2/9 0:34:36 Starting YOLOv3
=> Restoring weights from: YOLOv3\checkpoint\yolov3_coco_demo.ckpt ...
epoch 1 batch 1, train loss: 2450.6555
epoch 1 batch 2, train loss: 2449.2537
epoch 1 batch 3, train loss: 2446.446
epoch 1 batch 4, train loss: 2442.2456
System.NotSupportedException: Specified method is not supported.
   at NumSharp.NDArray.op_Implicit(Array array)
   at TensorFlowNET.Examples.ImageProcessing.YOLO.Dataset.Items()+MoveNext() in E:\workspace\net\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ObjectDetection\YOLOv3\Dataset.cs:line 115
   at TensorFlowNET.Examples.ImageProcessing.YOLO.SampleYOLOv3.Train() in E:\workspace\net\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ObjectDetection\YOLOv3\SampleYOLOv3.cs:line 102
   at TensorFlowNET.Examples.ImageProcessing.YOLO.SampleYOLOv3.Run() in E:\workspace\net\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ObjectDetection\YOLOv3\SampleYOLOv3.cs:line 71
   at TensorFlowNET.Examples.Program.Main(String[] args) in E:\workspace\net\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\Program.cs:line 76
2021/2/9 0:35:19 Completed YOLOv3
Example: YOLOv3 is Failed!
1 of 20 example(s) are completed.
```
